/*
 * agmet_mobile_version_update 
 *
 * version update
 *
 * OpenAPI spec version: 1.0.0-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class InitData : IEquatable<InitData>
    { 
        /// <summary>
        /// Gets or Sets RegionId
        /// </summary>
        [DataMember(Name="regionId")]
        public int? RegionId { get; set; }

        /// <summary>
        /// Gets or Sets RegionNm
        /// </summary>
        [DataMember(Name="regionNm")]
        public string RegionNm { get; set; }

        /// <summary>
        /// Gets or Sets FarmId
        /// </summary>
        [DataMember(Name="farmId")]
        public int? FarmId { get; set; }

        /// <summary>
        /// Gets or Sets Plant
        /// </summary>
        [DataMember(Name="plant")]
        public List<Plant> Plant { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InitData {\n");
            sb.Append("  RegionId: ").Append(RegionId).Append("\n");
            sb.Append("  RegionNm: ").Append(RegionNm).Append("\n");
            sb.Append("  FarmId: ").Append(FarmId).Append("\n");
            sb.Append("  Plant: ").Append(Plant).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((InitData)obj);
        }

        /// <summary>
        /// Returns true if InitData instances are equal
        /// </summary>
        /// <param name="other">Instance of InitData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InitData other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    RegionId == other.RegionId ||
                    RegionId != null &&
                    RegionId.Equals(other.RegionId)
                ) && 
                (
                    RegionNm == other.RegionNm ||
                    RegionNm != null &&
                    RegionNm.Equals(other.RegionNm)
                ) && 
                (
                    FarmId == other.FarmId ||
                    FarmId != null &&
                    FarmId.Equals(other.FarmId)
                ) && 
                (
                    Plant == other.Plant ||
                    Plant != null &&
                    Plant.SequenceEqual(other.Plant)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (RegionId != null)
                    hashCode = hashCode * 59 + RegionId.GetHashCode();
                    if (RegionNm != null)
                    hashCode = hashCode * 59 + RegionNm.GetHashCode();
                    if (FarmId != null)
                    hashCode = hashCode * 59 + FarmId.GetHashCode();
                    if (Plant != null)
                    hashCode = hashCode * 59 + Plant.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(InitData left, InitData right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(InitData left, InitData right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
