/*
 * agmet_mobile_version_update 
 *
 * version update
 *
 * OpenAPI spec version: 1.0.0-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 날짜별로 발생한 해당 지역의 재해에 대한 답변 내용
    /// </summary>
    [DataContract]
    public partial class SurveyContent : IEquatable<SurveyContent>
    { 
        /// <summary>
        /// 재해 종류에 따른 답변 | 답변 0은 설문 미완료 1은 모름 2은 발생 3는 발생없음
        /// </summary>
        /// <value>재해 종류에 따른 답변 | 답변 0은 설문 미완료 1은 모름 2은 발생 3는 발생없음</value>
        [DataMember(Name="water")]
        public int? Water { get; set; }

        /// <summary>
        /// 재해 종류에 따른 답변 | 답변 0은 설문 미완료 1은 모름 2은 발생 3는 발생없음
        /// </summary>
        /// <value>재해 종류에 따른 답변 | 답변 0은 설문 미완료 1은 모름 2은 발생 3는 발생없음</value>
        [DataMember(Name="lt")]
        public int? Lt { get; set; }

        /// <summary>
        /// 재해 종류에 따른 답변 | 답변 0은 설문 미완료 1은 모름 2은 발생 3는 발생없음
        /// </summary>
        /// <value>재해 종류에 따른 답변 | 답변 0은 설문 미완료 1은 모름 2은 발생 3는 발생없음</value>
        [DataMember(Name="wind")]
        public int? Wind { get; set; }

        /// <summary>
        /// 재해 종류에 따른 답변 | 답변 0은 설문 미완료 1은 모름 2은 발생 3는 발생없음
        /// </summary>
        /// <value>재해 종류에 따른 답변 | 답변 0은 설문 미완료 1은 모름 2은 발생 3는 발생없음</value>
        [DataMember(Name="freeze")]
        public int? Freeze { get; set; }

        /// <summary>
        /// 재해 종류에 따른 답변 | 답변 0은 설문 미완료 1은 모름 2은 발생 3는 발생없음
        /// </summary>
        /// <value>재해 종류에 따른 답변 | 답변 0은 설문 미완료 1은 모름 2은 발생 3는 발생없음</value>
        [DataMember(Name="ht")]
        public int? Ht { get; set; }

        /// <summary>
        /// 재해 종류에 따른 답변 | 답변 0은 설문 미완료 1은 모름 2은 발생 3는 발생없음
        /// </summary>
        /// <value>재해 종류에 따른 답변 | 답변 0은 설문 미완료 1은 모름 2은 발생 3는 발생없음</value>
        [DataMember(Name="burn")]
        public int? Burn { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SurveyContent {\n");
            sb.Append("  Water: ").Append(Water).Append("\n");
            sb.Append("  Lt: ").Append(Lt).Append("\n");
            sb.Append("  Wind: ").Append(Wind).Append("\n");
            sb.Append("  Freeze: ").Append(Freeze).Append("\n");
            sb.Append("  Ht: ").Append(Ht).Append("\n");
            sb.Append("  Burn: ").Append(Burn).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((SurveyContent)obj);
        }

        /// <summary>
        /// Returns true if SurveyContent instances are equal
        /// </summary>
        /// <param name="other">Instance of SurveyContent to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SurveyContent other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Water == other.Water ||
                    Water != null &&
                    Water.Equals(other.Water)
                ) && 
                (
                    Lt == other.Lt ||
                    Lt != null &&
                    Lt.Equals(other.Lt)
                ) && 
                (
                    Wind == other.Wind ||
                    Wind != null &&
                    Wind.Equals(other.Wind)
                ) && 
                (
                    Freeze == other.Freeze ||
                    Freeze != null &&
                    Freeze.Equals(other.Freeze)
                ) && 
                (
                    Ht == other.Ht ||
                    Ht != null &&
                    Ht.Equals(other.Ht)
                ) && 
                (
                    Burn == other.Burn ||
                    Burn != null &&
                    Burn.Equals(other.Burn)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Water != null)
                    hashCode = hashCode * 59 + Water.GetHashCode();
                    if (Lt != null)
                    hashCode = hashCode * 59 + Lt.GetHashCode();
                    if (Wind != null)
                    hashCode = hashCode * 59 + Wind.GetHashCode();
                    if (Freeze != null)
                    hashCode = hashCode * 59 + Freeze.GetHashCode();
                    if (Ht != null)
                    hashCode = hashCode * 59 + Ht.GetHashCode();
                    if (Burn != null)
                    hashCode = hashCode * 59 + Burn.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(SurveyContent left, SurveyContent right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(SurveyContent left, SurveyContent right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
