/*
 * agmet_mobile_version_update 
 *
 * version update
 *
 * OpenAPI spec version: 1.0.0-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 기상 특보 자료
    /// </summary>
    [DataContract]
    public partial class WeatherReport : IEquatable<WeatherReport>
    { 
        /// <summary>
        /// yyyy-MM-dd 00:00:00
        /// </summary>
        /// <value>yyyy-MM-dd 00:00:00</value>
        [DataMember(Name="date")]
        public string Date { get; set; }

        /// <summary>
        /// 기상특보
        /// </summary>
        /// <value>기상특보</value>
        [DataMember(Name="report")]
        public string Report { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class WeatherReport {\n");
            sb.Append("  Date: ").Append(Date).Append("\n");
            sb.Append("  Report: ").Append(Report).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((WeatherReport)obj);
        }

        /// <summary>
        /// Returns true if WeatherReport instances are equal
        /// </summary>
        /// <param name="other">Instance of WeatherReport to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WeatherReport other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Date == other.Date ||
                    Date != null &&
                    Date.Equals(other.Date)
                ) && 
                (
                    Report == other.Report ||
                    Report != null &&
                    Report.Equals(other.Report)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Date != null)
                    hashCode = hashCode * 59 + Date.GetHashCode();
                    if (Report != null)
                    hashCode = hashCode * 59 + Report.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(WeatherReport left, WeatherReport right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(WeatherReport left, WeatherReport right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
